### ISSUE TITLE
Error reporting in dev

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-cli#108]
Let's surface errors for faster dev cycles.

- [ ] Make sure sourcemaps work
- [x] Server startup errors
- [ ] Server render errors
- [x] Compilation errors
- [ ] Reload when server startup errors fixed
- [ ] Reload when server render errors fixed
- [ ] Reload when compilation errors fixed
- [ ] Trigger page updates for server startup errors
- [ ] Trigger page updates for server render errors
- [ ] Trigger page updates for compilation errors

**Comment by mlmorg** [comment]
What is the status of this?
