### ISSUE TITLE
Replace node-zopfli

### ISSUE THREAD

**Issue by rtsao** [fusionjs/fusion-cli#111]
The binary deps from this package are annoying to deal with, instead we should use something like
- https://github.com/gfx/universal-zopfli-js
- https://github.com/dfrankland/wasm-zopfli

**Comment by bmcmurray** [comment]
Any movement here? https://github.com/pierreinglebert/node-zopfli seems to be mostly abandoned and installs have stopped working (https://github.com/pierreinglebert/node-zopfli/issues)

**Comment by rtsao** [comment]
According to https://twitter.com/jdalton/status/951290001265864705 the gfx package looks the fastest so all else being equal it seems we’d probably want to use that!
