### ISSUE TITLE
Improve experience of working with node builtins

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-cli#254]
### Type of issue

Feature request

### Description

Using node builtins currently requires employing some hacks due to the way we manage tree shaking in conjunction with our webpack node configuration. We should improve the experience of using node builtins.

### Current behavior

```js
// some-plugin.js
import fs from 'fs';
import {createPlugin} from 'fusion-core';

export default createPlugin({
  deps: {},
  provides: () => {
    // do some things with fs...
  }
}}

// src/main.js
import somePlugin from './some-plugin';
__NODE__ && app.register(somePlugin):
```

Running `dev` results in: 

```
error: (client) ./src/some-plugin.js
Module not found: Error: Can't resolve 'fs' in ...
```

This happens for two reasons.
1. we don't tree shake in development, so `src/some-plugin.js` is included in the client bundle
2. we set the `node.fs` webpack config to be `false`

### Expected behavior

The build should work, but the plugin won't be registered.

### Steps to reproduce

1. scaffold a fusion app
2. create a plugin that imports fs
3. apply that plugin in __NODE__ only
4. run `fusion dev`

### Proposed Solution

Long term, we can investigate ways of supporting tree shaking in development. Short term, we should set all `node` builtins to be `empty` (where possible) for the client build. This will allow the user to import them, but with throw errors if the user tries to use them. 

NOTE: Unfortunately, problems often arise when certain node builtins are set to 'empty', specifically surrounding testing, so we may need to make exceptions in certain cases.

**Comment by lhorie** [comment]
I feel like this is a bug, not a feature request.

Re: proposed solution: how about writing a babel plugin that checks for `import ... from 'builtin'` and removes the import in browsers, using [this](https://github.com/juliangruber/builtins) or similar libs?

**Comment by ganemone** [comment]
> how about writing a babel plugin that checks for import ... from 'builtin' and removes the import in browsers, using this or similar libs?

I like that solution, but also I would prefer to have less to maintain, and I think the webpack config option is simpler.

**Comment by lhorie** [comment]
for the short term I'm ok with either, but it would be good to track the long term plan for this separately so we can prioritize that later

**Comment by mlmorg** [comment]
Short-term first. Create separate ticket for long-term solution.

**Comment by mlmorg** [comment]
Set fs to empty

**Comment by ganemone** [comment]
This is causing issues with some other builtins such as `tls` when attempting to use the `request` library. Until we have webpack 4, we should set all the node builtins which *do not* have a polyfill implementation to `empty`. This includes:

- child_process
- cluster
- dgram
- dns
- fs
- module
- net
- readline
- repl
- tls

See https://github.com/webpack/node-libs-browser and https://webpack.js.org/configuration/node/ for reference
