### ISSUE TITLE
starting a production build without NODE_ENV=production should throw

### ISSUE THREAD

**Issue by rtsao** [fusionjs/fusion-cli#325]
Some integration tests were starting a production build without setting `NODE_ENV=production` which meant the asset plugin was attempting to serve assets from `.fusion/development` (nonexistent) instead of `.fusion/production`.

This was encountered in the integration test in https://github.com/fusionjs/fusion-cli/pull/324 where JS assets were not loading correctly because of this.

Because the value for `process.env.NODE_ENV` is inlined in bundled code, any non-bundled references to this should always match, so at startup we should probably just fail immediately if it doesn't match the build-time value.

**Comment by AlexMSmithCA** [comment]
This looks to have been resolved by https://github.com/fusionjs/fusion-cli/pull/572, specifically the addition of the `getEnvBanner` helper:

https://github.com/fusionjs/fusion-cli/blame/master/build/get-webpack-config.js#L586-L599

**Comment by AlexMSmithCA** [comment]
I'll add a quick regression test to guard this in the future, but for now closing this issue.
