### ISSUE TITLE
Issues with chunk preloading

### ISSUE THREAD

**Issue by rtsao** [fusionjs/fusion-cli#327]
https://github.com/fusionjs/fusion-cli/issues/314 surfaced some issues that may still exist with chunk preloading. It appears that in some cases this can still be incorrect (e.g. the main chunk being preloaded twice instead of main+critical async chunk). More investigation needed.

**Comment by KevinGrandon** [comment]
@rtsao Please reopen if there's an actual error with chunk preloading.
