### ISSUE TITLE
Feature request: Option to not transpile node_modules

### ISSUE THREAD

**Issue by lassedamgaard** [fusionjs/fusion-cli#339]
With version 1.3.0 the build time for our project approximately tripled, going from ~10s to ~30s. This is due to the transpilation of node_modules added in https://github.com/fusionjs/fusion-cli/pull/300. The PR recognizes that this'll impact performance, but I do not think such a dramatic increase was expected.

In our case, the dependency on `antd` introduces the largest overhead, but I'd expect any real-life project to see a substantial hit on build time.

We are in the lucky position that we do not need to target "ES5 browsers" so the transpilation is not needed and therefor it would be awesome if we could disable it.

**Comment by rtsao** [comment]
We definitely plan to expose a config in the vein of https://github.com/browserslist/browserslist.

More long-term, there's an [RFC for per-browser bundles](https://github.com/fusionjs/rfcs/blob/browser-specific-bundles/text/0000-browser-specific-bundles.md) which in development will usually mean no transpilation at all.

Ideally, I think we could avoid adding configuration for `node_module` transpilation (i.e. the whole app bundle is always consistent to the same ES version)

**Comment by rtsao** [comment]
The performance impact should be mitigated by https://github.com/fusionjs/fusion-cli/pull/343, released since `1.4.0`, which I think should suffice until we have proper per-browser bundles. When we implement that, we will be able to greatly improve initial build times.
