### ISSUE TITLE
`dev --test` does not work

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-cli#444]
### Type of issue

Bug

### Description

When running `fusion dev --test` it should run tests on the initial build, and subsequently re-rerun tests for any changed files. Currently it fails with some errors about jest usage.

### Current behavior

Running `fusion dev --test` results in:

```
...
The --config option requires a JSON string literal, or a file path with a .js or .json extension.
Example usage: jest --config ./jest.config.js
```

### Expected behavior

The tests should run in the same way they would when running `fusion test`.

### Steps to reproduce

1. Scaffold a fusion project
2. run `fusion dev --test` or `yarn dev --test`

**Comment by mlmorg** [comment]
We won't do this.
