### ISSUE TITLE
Fusion.js could also look for $PORT to support Heroku more simply

### ISSUE THREAD

**Issue by brandoncc** [fusionjs/fusion-cli#464]
### Type of issue

Feature request

### Description

Fusion.js currently looks for `process.env.HTTP_PORT`. Heroku sets the current port as `$PORT`. That requires this Procfile:

```
web: ./node_modules/.bin/fusion start --port=${PORT:-3000}
```

If Fusion.js were to look for `$HTTP_PORT` || `$PORT` || 3000, it would allow Fusion.js apps to start on Heroku without a custom Procfile.

**Comment by iamveen** [comment]
👍

Also, apologies for being slightly off-topic but are you able to get fusion to build and run on Heroku using buildpacks? I'm having an issue where build artifacts contain absolute paths to `node_modules`, and because the app builds in `/tmp` and is then moved to `/app` the server fails to start.

**Comment by KevinGrandon** [comment]
> are you able to get fusion to build and run on Heroku using buildpacks

Brandon was pretty awesome and open sourced this buildpack: https://github.com/brandoncc/heroku-buildpack-fusionjs

We are most likely going to recommend using docker for deployment on Heroku. Hopefully one of these two solutions will work for you.

**Comment by iamveen** [comment]
Awesome thanks! I just finished setting up Docker too, but I'll give this buildpack a try.

**Comment by brandoncc** [comment]
@iamveen I'm sorry the buildpack didn't work for you. I actually just finished rewriting it, in case you would like to check it out.

It is no longer a fork of the heroku/nodejs buildpack. It now depends on it instead. If you would like to test it out, you can paste this in your terminal:

```
yarn create fusion-app test-fusion-app
cd test-fusion-app
echo "node_modules" >> .gitignore
echo ".fusion" >> .gitignore
git init
git add .
git commit -m "Create app"
heroku create
git push heroku master
heroku buildpacks:add -i 2 https://github.com/brandoncc/heroku-buildpack-fusionjs
git commit -m "Trigger deploy" --allow-empty
git push heroku master
heroku open
```

**Comment by brandoncc** [comment]
@iamveen Could I ask for more information about why the original build pack didn't work? Did you experience errors? Were you binding to `$PORT`? If you would, please post what your experience was as an issue on https://github.com/brandoncc/heroku-buildpack-fusionjs. Thanks!

**Comment by iamveen** [comment]
No need to apologize @brandoncc, in the end you still saved me with that sed command. I'll see if I can re-create that scenario and post the results as an issue. And thank you!

**Comment by mlmorg** [comment]
We'd like to stick to one env variable to keep it simple. We recommend using the buildpack referenced above. Thanks.
