### ISSUE TITLE
Support all Jest CLI onlyChanged option

### ISSUE THREAD

**Issue by supersonicclay** [fusionjs/fusion-cli#500]
### Type of issue

Feature request

### Description

Should be able to run tests with any of the jest CLI options. It appears with `fusion test --watch`, the `--watch` flag is passed through, but others aren't.

I'm specifically looking for `fusion test --onlyChanged` to work.

### Environment

fusion-cli@1.8.3

**Comment by KevinGrandon** [comment]
I don't think we will support all flags, but happy to whitelist flags as needed.
