### ISSUE TITLE
Treeshaking doesn't kick in if imported entity is used within compoung conditional

### ISSUE THREAD

**Issue by lhorie** [fusionjs/fusion-cli#526]
### Type of issue

bug

### Description

```js
// client-only.js
export default window.location.href;

// main.js
import w from './client-only';

if (__BROWSER__ && w.location.href) console.log(w.location.href)
```

Note: this is reproducible with `assumeNoImportSideEffects ` set to both true and false

### Current behavior

`ReferenceError: window is not defined`

### Expected behavior

Should not throw error on server

### Steps to reproduce

1. export a module that consumes a browser-only API
2. import that module from main.js
3. use it in a boolean expression whose left operand is `__BROWSER__`

### Your environment

* fusion-cli version: 1.8.3

* Node.js version (`node --version`): 8.12.0

* npm version (`npm --version`): 5.6.0

* Operating System: MacOS

**Comment by rtsao** [comment]
I'm unable to reproduce this with `assumeNoImportSideEffects: true`.

Without this option, unused imports can't be pruned.
