### ISSUE TITLE
Add better debug workflows for testing

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-cli#53]
We should have an easy way to run your tests in debug mode for both browser and node tests.

**Comment by supersonicclay** [comment]
It looks like `fusion test --debug` works for me. But `fusion test --debug --watch` does not hit my breakpoints.

**Comment by supersonicclay** [comment]
I was able to get debugging with watch working by passing the `--no-cache` flag to jest.
https://github.com/facebook/jest/issues/6683#issuecomment-417515963

Here's the full command that works for fusion.
```
JEST_ENV=dev node --inspect ./node_modules/.bin/jest --config=./node_modules/fusion-cli/build/jest/jest-config.js --runInBand --watch --no-cache
```

**Comment by KevinGrandon** [comment]
I think that this ticket was made before we had the `--debug` option, so going to close this for now. We will either add or passthrough `--no-cache` when debug is set.
