### ISSUE TITLE
Chunk naming of dynamic import does not work in production

### ISSUE THREAD

**Issue by rasmusprentow** [fusionjs/fusion-cli#530]
### Type of issue

Bug

### Description

Naming chunks using the following syntax only works in dev, and is ignored in production. 

 ```import(/* webpackChunkName: "somename" */ './file')```

Running `fusion dev` produces files in the `.fusion` dir consistent with the naming, but running with `fusion build` the names will be numeric as is the behaviour when `webpackChunkName` is not specified. 

### Your environment

* fusion-cli version: 1.10.4

**Comment by rtsao** [comment]
This has been fixed in master
