### ISSUE TITLE
It's difficult to debug compilation issues in with fusion-cli

### ISSUE THREAD

**Issue by vicapow** [fusionjs/fusion-cli#542]
I find it difficult to debug compilation issues with fusion-cli. I believe this has to do mainly with the caching and cache invalidation mechanism fusion users as well as how it stores those cached assets on disk.

* its not alway obvious when it's required to clear `node_modules/.fusion_babel-cache`. One posible solution woul be to add a `--no-cache` option as part of the cli tool.
* it's difficult to debug the compilation output of individual files in this cache because the output looks like...

````sh
-rw-r--r--     1 vp  staff   4.4K Oct  2 21:17 002fb2a2633b20d45d1a5747a19338d3.json.gz
-rw-r--r--     1 vp  staff   2.3K Oct  2 21:09 003fcf5aba12247fd24527e73f93bca6.json.gz
-rw-r--r--     1 vp  staff   1.2K Oct  2 21:09 0049a0ea213e3a7f47487f4f1bc6e2a7.json.gz
-rw-r--r--     1 vp  staff   3.5K Oct  2 21:17 0086eb17fc095562787d82ac42025a92.json.gz
```
I think the file makes should match the original source and the cache shas should be computed in a separate table.

**Comment by vicapow** [comment]
For reference, here is how Jest computes its cache keys so that if the babel config and other file changes will invalidate the cache: https://github.com/facebook/jest/blob/69654b579ee1666724ad5fa7caabf84838595b31/packages/babel-jest/src/index.js#L98

````js
      return crypto
        .createHash('md5')
        .update(THIS_FILE)
        .update('\0', 'utf8')
        .update(JSON.stringify(options))
        .update('\0', 'utf8')
        .update(fileData)
        .update('\0', 'utf8')
        .update(path.relative(rootDir, filename))
        .update('\0', 'utf8')
        .update(configString)
        .update('\0', 'utf8')
        .update(getBabelRC(filename))
        .update('\0', 'utf8')
        .update(instrument ? 'instrument' : '')
        .digest('hex');
````

**Comment by rtsao** [comment]
> its not alway obvious when it's required to clear `node_modules/.fusion_babel-cache`.

It sounds like there may be a bug; clearing the cache should never be necessary. Any change that should cause an invalidation should always yield a new cache key and thus be a cache miss.

FWIW, the cache key generation code in fusion-cli looks similar to Jest (thanks for posting that):

https://github.com/fusionjs/fusion-cli/blob/c653b90a127401eb4366afcaba79ab9b8b3f0642/build/loaders/babel-loader.js#L80-L91

Is there a reproducible example where cache invalidation is not working correctly? When cache invalidation doesn't work correctly, what is being changed? Are you changing file contents?

**Comment by mlmorg** [comment]
@vicapow can you provide a reproducible example?

**Comment by vicapow** [comment]
iirc this was happening when I was updating dependencies incrementally

**Comment by mlmorg** [comment]
Going to close without reproducible steps. Please reopen if you have a way to make this happen.

**Comment by vicapow** [comment]
`yarn upgrade` to reproduce

**Comment by KevinGrandon** [comment]
> `yarn upgrade` to reproduce

I have not been able to reproduce this using the open source, or internal, scaffold. If you could construct a minimal repository and provide a link to this we will be happy to spend some time investigating this.
