### ISSUE TITLE
Race condition with server side reloading

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-cli#608]
There is a race condition when making changes to server side code which can cause an EADDRINUSE error.

### Type of issue

Bug

### Description

There is a race condition when making changes to server side code which can result in an EADDRINUSE error when the old process has not exited yet, and a new process is started.

### Steps to reproduce

1. scaffold a fusion app
2. add the following snippet into `src/main.js`

```js
if (__NODE__) {
  process.on('SIGTERM', () => {
    console.log('Received KIll');
    setTimeout(() => {
      process.exit();
    }, 10000);
  });
}
```

3. save the `src/main.js` file a few times

**Comment by shanshanzhu** [comment]
If it helps: the EADDRINUSE shows up after rebuilding with code without error, it is gone when rebuilding an error-free code from the version of code that has error.

Is there any ETA for the fix?

**Comment by rtsao** [comment]
I can reproduce this every time using yarn v1.12.1, but when I downgrade to v1.7.0 the issue seems to go away.

Also, changing fusion-cli versions doesn't seem to make much difference (it seems wholly dependent on yarn) so I don't think this was a regression introduced anywhere.

**Comment by rtsao** [comment]
Yeah, seems to be a yarn issue: https://github.com/yarnpkg/yarn/issues/6608

**Comment by conradreuter** [comment]
For people using `patch-package` that are looking for a temporary fix without downgrading yarn:

Put the following file under `patches/fusion-cli+1.12.1.patch` and run `yarn`
https://gist.github.com/conradreuter/bcf252310a7ce848705d0f6a45f59b30
