### ISSUE TITLE
Publish sourcemaps for production

### ISSUE THREAD

**Issue by lxe** [fusionjs/fusion-cli#626]
### Type of issue

Feature Request

### Description

Publish meaningful sourcemaps for production instead of `empty-sourcemaps`. Sourcemaps do not get loaded until devtools are open and they are a useful debugging tool. 

### Current behavior

Production sourcemaps are empty

### Expected behavior

Production sourcemaps should not be empty

### Steps to reproduce

1. 
2.
3.

### Your environment

* fusion-cli version:

* Node.js version (`node --version`):

* npm version (`npm --version`):

* Operating System:

**Comment by rtsao** [comment]
Source maps are created in production. Do you mean you want source map comments in production JS files?

**Comment by lxe** [comment]
Closing in favor of a new ticket
