### ISSUE TITLE
Error stack traces in tests

### ISSUE THREAD

**Issue by rtsao** [fusionjs/fusion-cli#63]
Ensure this works nicely with error stack traces.

**Comment by rtsao** [comment]
Just to unpack this a bit, there's a cartesian product of a few factors that constitute this whole problem.

**Error type**
1. Unhandled synchronous errors
2. Unhandled promise rejections via async functions
3. Unhandled promise rejections

**Debugger**
1. No debugger attached (`fusion test-app`)
2. Chrome DevTools debugger attached (`fusion test-app --debug`)

**Environment**
1. Jest/node
2. Puppeteer/headless chrome

Notes:

- Puppeteer does [not apply sourcemaps to stack traces](https://github.com/GoogleChrome/puppeteer/issues/985).
- Chrome DevTools has built-in stack trace sourcemapping
- Node doesn't show unhandled promise rejection stack traces by default (`--trace-warnings` is needed), but Chrome DevTools does

**Comment by mlmorg** [comment]
We believe this is done.
