### ISSUE TITLE
fusion-cli introduces regressions to how commonJS modules are compiled

### ISSUE THREAD

**Issue by vicapow** [fusionjs/fusion-cli#632]
newer versions of fusion expect all node_module dependencies to support 'use_strict` which would be a breaking change. I'll be adding more detail here but creating the ticket now to track internally.

**Comment by vicapow** [comment]
likely the same as https://github.com/fusionjs/fusion-cli/issues/622

**Comment by rtsao** [comment]
Duplicate of https://github.com/fusionjs/fusion-cli/issues/627
