### ISSUE TITLE
Add support for uglifyOptions

### ISSUE THREAD

**Issue by cain-wang** [fusionjs/fusion-cli#639]
Our bedrock application have an extensive end-2-end test setup that relies on queries of React component names.
The reason we evolved to use component names  instead of class names is we are mostly testing on the React component level, not only on the DOM level. Because the React component props expose much more info than DOM in case of canvas drawings. And React APIs only support component query based on names, not DOM attributes:

Our test scripts look like this:

```
// click layer manager button
auto.click('IconButton[icon=layers]');
// wait for layers panels to open
const layersPanel = await auto.waitFor('LayersPanel');
// turn on geofence layer
auto.click('LayersPanel Switch:contains(Geofence)')
```

https://reactjs.org/docs/test-utils.html#findrenderedcomponentwithtype

It would be great if we can support uglifyOptions in fusion so we can specify keep_fnames to retain React component names after the build.

**Comment by KevinGrandon** [comment]
Totally understand your pain point here and we have plans to solve this. We are going to implement an "enzyme-like" APIs which allow you to query DOM nodes by an element reference. I believe that will solve your use-case, but it will still be a while before we get to that work.

For internal tracking of this work, please see task: WPT-594

**Comment by cain-wang** [comment]
Thanks for the rely, Kevin! A enzyme-like APIs would be really cool!
As our apps have extensive 200+ e2e test cases being blocked right now. Do you think it's possible to enable this so that our tests won't be lost all of sudden?

**Comment by austintang** [comment]
@KevinGrandon 
We've written a significant number of test cases that uses a custom react component querying library.
These test cases currently cannot be run in our production environments because of minification. It would help us tremendously if you could make minification configurable.
