### ISSUE TITLE
Sourcemap is corrupted for injected dependencies

### ISSUE THREAD

**Issue by cain-wang** [fusionjs/fusion-cli#644]
I was trying to debug web-rpc-redux's createRPCThunk() by adding a break at @uber/web-rpc-redux/dist-es/index.js, right before the line

https://code.uberinternal.com/diffusion/WEWEBRPC/browse/master/src/actions.js$115

```
return rpc(rpcId, params, function (err, resp) {
```

When I tried to step into rpc(), the Chrome debugger opened some weird path http://localhost:7285/Users/$username/dev/web-monorepo/services/src/index.js

with source content as below:

```
import server from './server';
import browser from './browser';
import UberWebEventCookie from './cookie-types/uber-web-event';

declare var __NODE__: Boolean;
export default (__NODE__ ? server : browser);

export {UberWebEventCookie};
export {AnalyticsCookieTypeToken, AnalyticsSessionToken} from './tokens';
```

I believe this might be caused by the fact that the rpc variable was injected into Redux by Fusion.
This makes the debugging super tricky and people need to `grep` rpc.toString() in the Chrome console to find where rpc() was defined.

Our dependency versions:

@uber/web-rpc-redux@9.0.0
fusion-cli@1.12.1
fusion-core@1.10.0

**Comment by derekjuber** [comment]
@cain-wang: Looking into this now but is there a reason why you aren't using `fusion-plugin-rpc` as the basis for Redux in Fusion?

**Comment by derekjuber** [comment]
New versions of fusion-plugin-web-rpc-compat and fusion-plugin-rpc have been submitted and will be published with our regular release cycle. This should address your specific issue.

Going forwards we'll need to publish new versions of all of our modules so that source maps will work with them. Thanks for reporting this and sorry for taking so long on this.
