### ISSUE TITLE
Add Support for web workers

### ISSUE THREAD

**Issue by mrmuhammadali** [fusionjs/fusion-cli#663]
### Type of issue

Feature Request

### Description

Add support for web workers by default. [workerize-loader](https://github.com/developit/workerize-loader) or [worker-loader](https://github.com/webpack-contrib/worker-loader) are great webpack plugins for this purpose.

**Comment by KevinGrandon** [comment]
I believe the main issue is that we want to include bundling of the service worker? So imports from other files?

**Comment by mrmuhammadali** [comment]
How worker-loader works is, it resolves all of the dependencies and creates separate bundle for each worker file, so yes.

**Comment by KevinGrandon** [comment]
This is now implemented in master: https://github.com/fusionjs/fusion-cli/pull/720

Documented here: https://github.com/fusionjs/fusionjs.github.io/pull/109
