### ISSUE TITLE
Better release notes or changelog

### ISSUE THREAD

**Issue by NameFILIP** [fusionjs/fusion-cli#703]
This is not very helpful:
![image](https://user-images.githubusercontent.com/834796/52893447-06573000-3151-11e9-9129-b4b6afda912d.png)

The current approach complicates library updates because I have to scan several Release pages and combine all changes between versions into a list which decreases a probability of me doing it.

**Comment by rtsao** [comment]
Agreed, I think it would be better if pre-releases were ignored for changelog purposes, so then release notes for actual releases would contain the full list of changes.
