### ISSUE TITLE
Tests running out of memory after adding codecov

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-cli#88]
After introducing code coverage[1] we started seeing memory issues on Buildkite. Possibly due to subprocess instrumentation, need to investigate.

[1]https://github.com/fusionjs/fusion-cli/commit/b1bcee76f503221b59b476363e74d0deedc33636

**Comment by mlmorg** [comment]
Seems like this is no longer a priority so moving to backlog.
